-- ============================================================================
-- SCRIPT DE DATOS SEMILLA PARA EL AGENDADOR DE CITAS
-- 25 Médicos y 100 Pacientes
-- ============================================================================
-- Ejecutar en el SQL Editor de Supabase para poblar las tablas.
-- AVISO: Si ya existen datos, se omitirán los INSERTs conflictivos.
-- ============================================================================

-- ============================================================================
-- 25 MÉDICOS CON ESPECIALIDADES VARIADAS
-- ============================================================================
INSERT INTO doctors (name, specialty) VALUES
('Dr. Ricardo Aguirre', 'Cardiología'),
('Dra. Beatriz Álvarez', 'Medicina Interna'),
('Dr. Carlos Bautista', 'Neumología'),
('Dra. Daniela Bravo', 'Gastroenterología'),
('Dr. Eduardo Campos', 'Traumatología'),
('Dra. Fabiola Castillo', 'Pediatría'),
('Dr. Gabriel Contreras', 'Urología'),
('Dra. Helena Cruz', 'Dermatología'),
('Dr. Ignacio Delgado', 'Oftalmología'),
('Dra. Jazmín Díaz', 'Neurología'),
('Dr. Kevin Espinoza', 'Psiquiatría'),
('Dra. Leticia Fernández', 'Endocrinología'),
('Dr. Mario Flores', 'Cirugía General'),
('Dra. Natalia García', 'Reumatología'),
('Dr. Óscar Hernández', 'Oncología'),
('Dra. Patricia Jiménez', 'Nefrología'),
('Dr. Rafael López', 'Medicina Deportiva'),
('Dra. Silvia Márquez', 'Hematología'),
('Dr. Tomás Medina', 'Anestesiología'),
('Dra. Úrsula Moreno', 'Geriatría'),
('Dr. Víctor Navarro', 'Neurocirugía'),
('Dra. Ximena Ortega', 'Infectología'),
('Dr. Yair Peña', 'Medicina Familiar'),
('Dra. Zaida Quintero', 'Alergología'),
('Dr. Adrián Ríos', 'Medicina de Urgencias');

-- ============================================================================
-- 100 PACIENTES
-- ============================================================================
INSERT INTO patients (name) VALUES
('Abigail Ramírez'),
('Alejandro Soto'),
('Alicia Vargas'),
('Andrés Torres'),
('Antonia Reyes'),
('Arturo Flores'),
('Bárbara Méndez'),
('Benjamín Rivas'),
('Camila Herrera'),
('César Castillo'),
('Claudia Vega'),
('Cristian Peña'),
('Daisy Guerrero'),
('Daniel Paredes'),
('Diana Salazar'),
('Diego Cervantes'),
('Dulce Nava'),
('Edgar Zamora'),
('Elena Orozco'),
('Emilio Rangel'),
('Erica Tovar'),
('Ernesto Luna'),
('Esperanza Galván'),
('Esteban Ponce'),
('Florencia Ávila'),
('Francisco Medrano'),
('Gabriela Zavala'),
('Gerardo Mondragón'),
('Gloria Escobar'),
('Gustavo Carranza'),
('Helena Robles'),
('Héctor Saavedra'),
('Irene Santillán'),
('Ismael Zúñiga'),
('Itzel Águila'),
('Iván Llamas'),
('Jaime Cervantes'),
('Julia Esparza'),
('Karen Ibarra'),
('Leonardo Rendón'),
('Liliana Garza'),
('Lorenzo Ferrer'),
('Lourdes Villalobos'),
('Luis Miguel Pérez'),
('Manuela Acosta'),
('Marco Luján'),
('Margarita Urbina'),
('Mauricio Segura'),
('Mireya Beltrán'),
('Néstor Roldán'),
('Noemí Cisneros'),
('Octavio Lemus'),
('Olga Nájera'),
('Pablo Covarrubias'),
('Paloma Saldaña'),
('Paola Arreola'),
('Raquel Godínez'),
('Renata Pineda'),
('Ricardo Valadez'),
('Rita Gallegos'),
('Roberto Zepeda'),
('Rocío Cardona'),
('Rodrigo Ballesteros'),
('Rosa María Solano'),
('Rubén Alarcón'),
('Salvador Tejeda'),
('Sandra Quiroz'),
('Santiago Becerra'),
('Sara Espino'),
('Saúl Montero'),
('Silvia Treviño'),
('Sociedad Palacios'),
('Sofía Valenzuela'),
('Tania Coronado'),
('Teodoro Anguiano'),
('Valeria Cárdenas'),
('Vicente Ayala'),
('Victoria Linares'),
('Violeta Huerta'),
('Viridiana Prado'),
('Xavier Escamilla'),
('Yadira Serrano'),
('Yolanda Bernal'),
('Zacarías Ojeda'),
('Alan Godínez'),
('Brenda Almanza'),
('Carlos Santacruz'),
('Daniela Fajardo'),
('Enrique Borja'),
('Fernanda Lemus'),
('Graciela Noriega'),
('Humberto Anaya'),
('Jimena Regalado'),
('Jorge Luis Campos'),
('Karla Manríquez'),
('Luis Ángel Franco'),
('María José Rocha'),
('Nadia Téllez'),
('Óscar Daniel Maya'),
('Paulina Rendón'),
('Ramiro Quintero'),
('Ximena Saucedo');
